---
title: "splice_sim figure 2"
author: "Tobias Neumann"
always_allow_html: yes
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float: yes
  word_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(tidyverse)
library(gridExtra)
library(DESeq2)
library(RColorBrewer)
library(ggrepel)
library(GGally)
library(biomaRt)
library(pheatmap)
library(UpSetR)
library(dupRadar)
library(Rsamtools)
library(DT)
library(ineq)
library(pracma)

datapal = brewer.pal(5, "Set1")

```

# Big3 old

```{r}

eval = read_tsv('../../myProjects/slamdunk/splice_sim/big3/big3/eva/tid_performance.tsv')

eval = eval %>% mutate(
  precision=TP/(TP+FP), 
  recall=TP/(TP+FN), 
  F1=2*TP/(2*TP+FP+FN))

eval %>%
  dplyr::filter(!is.na(mapper)) %>%
  ggplot(aes(x = condition, y = F1, fill = mapper)) + 
  geom_violin() +
  geom_boxplot(position = position_dodge(width = 0.9), width=.1, outlier.shape = NA) +
  facet_wrap(iso~is_converted) +
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.title = element_blank()
  ) +
  scale_fill_brewer(palette = "Set1")

```

# Small5

```{r}

eval = read_tsv('../../myProjects/slamdunk/splice_sim/small5_2/small5/eva/tid_performance.tsv')

eval = eval %>% mutate(
  precision=TP/(TP+FP), 
  recall=TP/(TP+FN), 
  F1=2*TP/(2*TP+FP+FN))

eval %>%
  dplyr::filter(!is.na(mapper)) %>%
  ggplot(aes(x = condition, y = F1, fill = mapper)) + 
  geom_violin() +
  geom_boxplot(position = position_dodge(width = 0.9), width=.1, outlier.shape = NA) +
  facet_wrap(iso~is_converted) +
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.title = element_blank()
  ) +
  scale_fill_brewer(palette = "Set1")

```

# Big3 Biseq

```{r}

eval = read_tsv('../../myProjects/slamdunk/splice_sim/big3_biseq/big3_biseq/eva/tid_performance.tsv')

eval = eval %>% mutate(
  precision=TP/(TP+FP), 
  recall=TP/(TP+FN), 
  F1=2*TP/(2*TP+FP+FN))

eval %>%
  dplyr::filter(!is.na(mapper)) %>%
  ggplot(aes(x = condition, y = F1, fill = mapper)) + 
  geom_violin() +
  geom_boxplot(position = position_dodge(width = 0.9), width=.1, outlier.shape = NA) +
  facet_wrap(iso~is_converted) +
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.title = element_blank()
  ) +
  scale_fill_brewer(palette = "Set1")

```

# Big3 Slamseq

```{r}

eval = read_tsv('../../myProjects/slamdunk/splice_sim/big3_slamseq/big3_slamseq/eva/tid_performance.tsv')

eval = eval %>% mutate(
  precision=TP/(TP+FP),
  recall=TP/(TP+FN),
  F1=2*TP/(2*TP+FP+FN))

eval %>%
  dplyr::filter(!is.na(mapper)) %>%
  ggplot(aes(x = condition, y = F1, fill = mapper)) +
  geom_violin() +
  geom_boxplot(position = position_dodge(width = 0.9), width=.1, outlier.shape = NA) +
  facet_wrap(iso~is_converted) +
  theme_linedraw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.title = element_blank()
  ) +
  scale_fill_brewer(palette = "Set1")

```
