---
title: "splice_sim_xcyc_analysis.Rmd"
author: "niko.popitsch@imba.oeaw.ac.at"
documentclass: article
fontsize: 10pt
output:
  pdf_document:
    fig_width: 12
    fig_height: 10
    fig_caption: true
  html_document:
    toc: true
    toc_float: true
    fig_width: 14
    fig_height: 10
    fig_caption: true
    df_print: paged
params:
    data_dir:
       value: "/Volumes/groups/ameres/Niko/projects/Ameres/splicing/splice_sim/testruns/big4_slamseq_nf_kss/xcyc_analysis/"
    out_dir:
       value: "/Volumes/groups/ameres/Niko/projects/Ameres/splicing/splice_sim/splice_sim_paper/analysis_kss/"
---
<style type="text/css">
body, td {
   font-size: 10px;
}
code.r{
  font-size: 10px;
}
pre {
  font-size: 10px
}
div.blue pre { background-color:lightblue; }
div.blue pre.r { background-color:blue; }
</style>

<!--
rmarkdown::render('splice_sim_decay_analysis.Rmd', 'html_document')
-->

# INIT

```{r setup, include=FALSE}
require(data.table)
require(tidyr)
require(dplyr)
require(ggplot2)
require(scales)
require(rjson)
require(stringr)
require(VGAM)
require(cowplot)
require(arrow)
require(tictoc)
require(ggpubr)
require(rstatix)
require(minpack.lm)
require(readr)
require(testthat)
require(RColorBrewer)
require(skimr)
require(ggforce)
require(writexl)
require(xfun)
require(forcats)
require(tibble)
# NB install arrow with snappy on Rstudio server
# Sys.setenv(ARROW_WITH_SNAPPY = "ON")
# Sys.setenv(NOT_CRAN="true")
# Sys.setenv(LIBARROW_BINARY="FALSE")
# install.packages("arrow", repos = "https://arrow-r-nightly.s3.amazonaws.com")

# to ensure stripping '\0' (nul) from character vector
options(arrow.skip_nul = TRUE)

# global theme
ggplot2::theme_set(theme_light())

# enable tidylog (has overhead!)
#require(tidylog)
# turn tidylog off
options("tidylog.display" = list()) 

# load resources/functions
source('splice_sim_resources.R')
```


# data

```{r data, include=F, echo=F, cache=T, eval=F}

# create result dir?
if (!dir.exists(params$out_dir)) {
  dir.create(params$out_dir)
} 

# ===========================================================
# load data files
# ===========================================================
sample_sheet = load_table(paste0(params$data_dir, 'sample_sheet.tsv')) 

# load slamstr counts
hist=tibble()
for ( bam in sample_sheet$bam) {
  hist = hist %>% bind_rows(load_table(paste0(params$data_dir, '/results/xcyc_',bam,'.hist.tsv.gz')) )
}
hist = hist %>% left_join(sample_sheet, by='bam') %>% 
  mutate(diff = yc-xc,
         class=case_when(
           xc==0 & yc>0 ~ 'FP',
           yc==0 & xc>0 ~ 'FN',
           TRUE ~ 'TP'
         )
  )

```

# hist plots

```{r}

p1 = hist %>% ggplot(aes(xc, yc)) +
  geom_abline(intercept = 0, slope = 1, col='red', linetype='dotted') +
  geom_tile(aes(fill = count)) +
  facet_grid(mapper~cr) + 
  scale_fill_gradient2( trans = 'log' ) +
  xlab("Simulated T/C conversions") +
  ylab("Observed T/C conversions") +
  ggtitle("Simulated vs observed T/C conversions for FP reads") +
  guides(fill=guide_legend(title="Counts"))

tab = hist %>% group_by(mapper, cr, class) %>% summarise(c=sum(count)) %>% ungroup() %>% 
  group_by(mapper, cr) %>% mutate(sumc=sum(c)) %>% mutate(frac=c/sumc)

p2 = tab %>% 
  ggplot(aes(class,frac,fill=mapper)) +
  geom_col() +
  facet_grid(mapper~cr) +
  my_scales() +
  ggtitle("FP/FN/TP labeling for FP reads ") + 
  theme(legend.position="none") +
  ylab("Fraction") + xlab("")

# tab = hist %>%  group_by(mapper, cr, diff) %>% summarise(c=sum(count))
# tab %>% ggplot(aes(diff,c,fill=mapper)) +
#   geom_col() +
#   facet_grid(mapper~cr) +
#   my_scales() +
#   xlim(-10,10) +
#   scale_y_log10() 

plot_grid(p1, p2,  labels = c('A','B'), ncol=1)
ggsave(paste0(params$out_dir, 'special_xc_yc_analysis.pdf'), width=12, height=9)

```

