name: splice_sim
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - sortedcontainers
  - samtools=1.14
  - sambamba
  - pandas
  - scipy
  - scikit-learn
  - more-itertools
  - joblib
  - python-intervaltree
  - biopython
  - bedtools
  - pysam
  - pyranges
  - pybedtools
  - art
  - star=2.5.2a
  - biobambam
  - tqdm
  - rseqc
  - transdecoder
  - conda-forge::r-base=4.1.2
  - multiqc
  - pyarrow
  - fastparquet
  - gff3sort
  - genmap
  - vcfpy
